### ISSUE TITLE
Compile error with 4.9 linaro toolchain.

### ISSUE THREAD

**Issue by vonfritz** [xapp-le/u-boot#2]
compiling u-boot (master-branch) with an 4.9 linaro toolchain gives:

./dwc3/owl_dwc3.c: In function 'dwc3_phy_init':
owl_dwc3.c:469:52: error: macro "**TIME**" might prevent reproducible builds [-Werror=date-time]
    printk(" GS705A phy init for dwc3 gadget %s\n", **TIME** );
                                                    ^
./dwc3/owl_dwc3.c:492:45: error: macro "**TIME**" might prevent reproducible builds [-Werror=date-time]
    printk(" GS705A phy init for xhci %s\n", **TIME** );

It builds with EXTRA_CFLAGS="-Wno-error=date-time"

**Comment by william-wyliang** [comment]
Ah, I actually have ever fixed this bug before the repository has formally released. Let me see if I can get it back.

**Comment by vonfritz** [comment]
Thank's works now without EXTRA_CFLAGS="-Wno-error=date-time"
