### ISSUE TITLE
making a bootable sdcard following the http://wiki.linux-xapple.org/w/index.php/Build_Howto does not work.

### ISSUE THREAD

**Issue by vonfritz** [xapp-le/u-boot#3]
Well when I try to make a bootable sdcard using the "new" master branch then:
http://pastebin.com/dRjqhxzS
This has worked before with the "old" master branch.

**Comment by vonfritz** [comment]
reverting this commit:
https://github.com/xapp-le/u-boot/commit/6200bb7643b098a95175572660674f28a676dc15
fix it!

**Comment by william-wyliang** [comment]
Thanks for the founding! Already reverted.
